[2023-10-20 23:28:31,137] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-20 23:28:31,155] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-20 23:28:31,156] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:28:31,158] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-10-20 23:28:31,159] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:28:31,186] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2023-10-10 00:00:00+00:00
[2023-10-20 23:28:31,191] {standard_task_runner.py:52} INFO - Started process 719 to run task
[2023-10-20 23:28:31,195] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2023-10-10T00:00:00+00:00', '--job-id', '1323', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpsy9c_d7w', '--error-file', '/tmp/tmpt58ntwy5']
[2023-10-20 23:28:31,197] {standard_task_runner.py:80} INFO - Job 1323: Subtask segunda_tarea
[2023-10-20 23:28:31,325] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-10-10T00:00:00+00:00 [running]> on host dfdda228c9fc
[2023-10-20 23:28:31,454] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-10T00:00:00+00:00
[2023-10-20 23:28:31,456] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-10-20 23:28:31,458] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-10-20 23:28:31,475] {subprocess.py:85} INFO - Output:
[2023-10-20 23:28:31,479] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-10-20 23:28:31,480] {subprocess.py:96} INFO - Command exited with return code 0
[2023-10-20 23:28:31,530] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20231010T000000, start_date=20231020T232831, end_date=20231020T232831
[2023-10-20 23:28:31,575] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-20 23:28:31,635] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-20 23:28:31,677] {dagrun.py:564} INFO - Marking run <DagRun mi_primer_dag_v3 @ 2023-10-10 00:00:00+00:00: scheduled__2023-10-10T00:00:00+00:00, externally triggered: False> successful
[2023-10-20 23:28:31,678] {dagrun.py:624} INFO - DagRun Finished: dag_id=mi_primer_dag_v3, execution_date=2023-10-10 00:00:00+00:00, run_id=scheduled__2023-10-10T00:00:00+00:00, run_start_date=2023-10-20 23:28:29.774497+00:00, run_end_date=2023-10-20 23:28:31.678176+00:00, run_duration=1.903679, state=success, external_trigger=False, run_type=scheduled, data_interval_start=2023-10-10 00:00:00+00:00, data_interval_end=2023-10-11 00:00:00+00:00, dag_hash=4b9501eea8320e392c62474f04ca2d17
