[2023-10-20 23:23:25,646] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-08-16T00:00:00+00:00 [queued]>
[2023-10-20 23:23:25,664] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-08-16T00:00:00+00:00 [queued]>
[2023-10-20 23:23:25,665] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:23:25,666] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-10-20 23:23:25,669] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:23:25,695] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2023-08-16 00:00:00+00:00
[2023-10-20 23:23:25,700] {standard_task_runner.py:52} INFO - Started process 3741 to run task
[2023-10-20 23:23:25,704] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2023-08-16T00:00:00+00:00', '--job-id', '1150', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmp6bbqezhk', '--error-file', '/tmp/tmp905yqz4b']
[2023-10-20 23:23:25,705] {standard_task_runner.py:80} INFO - Job 1150: Subtask segunda_tarea
[2023-10-20 23:23:25,800] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2023-10-20 23:23:25,824] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3741. PIDs of all processes in the group: [3741]
[2023-10-20 23:23:25,826] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3741
[2023-10-20 23:23:25,841] {process_utils.py:75} INFO - Process psutil.Process(pid=3741, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='23:23:25') (3741) terminated with exit code Negsignal.SIGTERM
[2023-10-20 23:23:25,844] {local_task_job.py:156} INFO - Task exited with return code 143
[2023-10-20 23:23:25,915] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20230816T000000, start_date=20231020T232325, end_date=20231020T232325
[2023-10-20 23:23:25,990] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
