[2023-10-20 23:28:31,151] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-10-09T00:00:00+00:00 [queued]>
[2023-10-20 23:28:31,169] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-10-09T00:00:00+00:00 [queued]>
[2023-10-20 23:28:31,170] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:28:31,171] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-10-20 23:28:31,172] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:28:31,194] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2023-10-09 00:00:00+00:00
[2023-10-20 23:28:31,201] {standard_task_runner.py:52} INFO - Started process 720 to run task
[2023-10-20 23:28:31,206] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2023-10-09T00:00:00+00:00', '--job-id', '1322', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpu0lear2f', '--error-file', '/tmp/tmp39cf_7dw']
[2023-10-20 23:28:31,208] {standard_task_runner.py:80} INFO - Job 1322: Subtask segunda_tarea
[2023-10-20 23:28:31,333] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-10-09T00:00:00+00:00 [running]> on host dfdda228c9fc
[2023-10-20 23:28:31,459] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-10-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-09T00:00:00+00:00
[2023-10-20 23:28:31,461] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-10-20 23:28:31,463] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-10-20 23:28:31,480] {subprocess.py:85} INFO - Output:
[2023-10-20 23:28:31,483] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-10-20 23:28:31,484] {subprocess.py:96} INFO - Command exited with return code 0
[2023-10-20 23:28:31,543] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20231009T000000, start_date=20231020T232831, end_date=20231020T232831
[2023-10-20 23:28:31,579] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-20 23:28:31,635] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-20 23:28:31,678] {dagrun.py:564} INFO - Marking run <DagRun mi_primer_dag_v3 @ 2023-10-09 00:00:00+00:00: scheduled__2023-10-09T00:00:00+00:00, externally triggered: False> successful
[2023-10-20 23:28:31,680] {dagrun.py:624} INFO - DagRun Finished: dag_id=mi_primer_dag_v3, execution_date=2023-10-09 00:00:00+00:00, run_id=scheduled__2023-10-09T00:00:00+00:00, run_start_date=2023-10-20 23:28:29.647273+00:00, run_end_date=2023-10-20 23:28:31.679982+00:00, run_duration=2.032709, state=success, external_trigger=False, run_type=scheduled, data_interval_start=2023-10-09 00:00:00+00:00, data_interval_end=2023-10-10 00:00:00+00:00, dag_hash=4b9501eea8320e392c62474f04ca2d17
